### PR TITLE
fixing issue in react-native-redash

### PR DESCRIPTION
**Pull request by Alarees**
fixing issue in `react-native-redash`
`react-native-redash` has issue with `react-native-reanimated` lib as in [Here](https://github.com/wcandillon/react-native-redash/issues/429)

and update the `redash` lib fix this issue and #110

### CODE REVIEW

**Comment by getinnocuous** [comment]
Would it be possible to get this merged soon please? 🙏

**Comment by gorhom** [comment]
thanks @Alarees for submitting this pr 👍

**Comment by elliotcinch** [comment]
Amazing. Cheers fellas

**Comment by aganov** [comment]
@gorhom is this reverted? Is it possible to reapply it, we are using both `animated-tabbar` and `bottom-sheet` libs and fixing redash to `v14` is preventing us to update reanimated to `v2.2.0`...

**Comment by darkbasic** [comment]
I was wondering the same, why is it reverted? I was hoping 2.1.2 would have allowed me to get rid of yarn resolutions but it still doesn't work out of the box...

**Pull request merged**
