### PR TITLE
chore: support icon class component

### PR DESCRIPTION
**Pull request by gorhom**
closing #39

### CODE REVIEW

**Comment by gorhom** [comment]
hi @efec89, could you test this PR if it fixes your issue.

```bash
yarn add ssh://git@github.com:gorhom/react-native-animated-tabbar#feature/support-icon-class-component
```

**Comment by efec89** [comment]
Screenshot_1590409918

**Comment by gorhom** [comment]
hi @efec89 , could post your implementation here, i'll try to reproduce it

**Comment by efec89** [comment]
@gorhom  I refresh project and works. I think cached. You can confirm this build to others.

**Comment by gorhom** [comment]
@efec89 good to hear 👍

**Pull request merged**
